# -*- encoding: utf-8 -*-
##############################################################################
#
#    GRAP - Change Account Move Lines Module for Odoo
#    Copyright (C) 2013-Today GRAP (http://www.grap.coop)
#    @author Julien WESTE
#    @author Sylvain LE GAL (https://twitter.com/legalsylvain)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

- !record {model: product.product, id: product_1_account_1}:
    name: Product 1 Account 1
    property_account_income: account.a_sale
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    list_price: 2

- !record {model: product.product, id: product_2_account_1}:
    name: Product 2 Account 1
    property_account_income: account.a_sale
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    list_price: 30

- !record {model: product.product, id: product_3_account_2}:
    name: Product 3 Account 2
    property_account_income: account.income_fx_income
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    list_price: 4

- !record {model: product.product, id: product_4_account_2}:
    name: Product 4 Account 2
    property_account_income: account.income_fx_income
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    list_price: 50
