language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"
  - VERSION="7.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install bzr wkhtmltopdf python-smbc
  - sudo pip install GitPython bzr cairosvg unidecode

install:
  - git clone https://github.com/OCA/web.git $HOME/web -b 7.0
  - git clone https://github.com/OCA/pos.git $HOME/pos -b 7.0
  - bzr branch lp:openerp-french-localization/7.0 $HOME/openerp-french-localization
  - git clone https://github.com/grap/odoo-addons-cis.git $HOME/odoo-addons-cis -b 7.0
  - git clone https://github.com/grap/odoo-addons-cpo.git $HOME/odoo-addons-cpo -b 7.0
  - git clone https://github.com/grap/odoo-addons-misc.git $HOME/odoo-addons-misc -b 7.0
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls
